packages:
  - packages/web-storybook
  - packages/cloudflare-worker
  - packages/web-app
allowBuilds:
  esbuild: false
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260906.1'
