import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const root = resolve(import.meta.dirname, "../..");
const readJson = (path) => readFile(resolve(root, path), "utf8").then(JSON.parse);
const tokens = await readJson("design-system/tokens.json");
const contracts = await readJson("design-system/contracts/primitives.json");
const flat = new Map();
function collect(node, path = []) {
  if (node && typeof node === "object" && "$value" in node) flat.set(path.join("."), node);
  else Object.entries(node).filter(([key]) => !key.startsWith("$")).forEach(([key, value]) => collect(value, [...path, key]));
}
collect(tokens);
const resolveValue = (value, seen = new Set()) => {
  if (typeof value !== "string") return value;
  const match = value.match(/^\{(.+)}$/);
  if (!match) return value;
  if (seen.has(match[1]) || !flat.has(match[1])) throw new Error(`Invalid token reference: ${value}`);
  return resolveValue(flat.get(match[1]).$value, new Set([...seen, match[1]]));
};
for (const token of flat.values()) resolveValue(token.$value);
const contrast = (foreground, background) => {
  const luminance = (hex) => hex.match(/[A-Fa-f0-9]{2}/g).map((part) => Number.parseInt(part, 16) / 255).map((channel) => channel <= 0.03928 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4).reduce((sum, channel, index) => sum + channel * [0.2126, 0.7152, 0.0722][index], 0);
  const [lighter, darker] = [luminance(foreground), luminance(background)].sort((a, b) => b - a);
  return (lighter + 0.05) / (darker + 0.05);
};
for (const [foreground, background] of [["theme.light.text.primary", "theme.light.surface.base"], ["theme.light.text.onAction", "theme.light.action.primary"], ["theme.light.text.onAction", "theme.light.action.danger"], ["theme.dark.text.primary", "theme.dark.surface.base"], ["theme.dark.text.onAction", "theme.dark.action.primary"]]) {
  const ratio = contrast(resolveValue(flat.get(foreground).$value), resolveValue(flat.get(background).$value));
  if (ratio < 4.5) throw new Error(`WCAG AA contrast failure for ${foreground} on ${background}: ${ratio.toFixed(2)}:1`);
}
const kebab = (value) => value.replace(/([a-z])([A-Z])/g, "$1-$2").replaceAll(".", "-").toLowerCase();
const cssValue = (token) => token.$type === "dimension" ? `${token.$value / 16}rem` : token.$type === "duration" ? `${token.$value}ms` : token.$type === "typography" ? `${token.$value.fontSize / 16}rem/${token.$value.lineHeight / 16}rem ${token.$value.fontWeight}` : Array.isArray(token.$value) ? `cubic-bezier(${token.$value.join(", ")})` : resolveValue(token.$value);
const cssTokens = [...flat].map(([name, token]) => `  --pa-${kebab(name)}: ${cssValue(token)};`).join("\n");
const themed = (theme) => [...flat].filter(([name]) => name.startsWith(`theme.${theme}.`)).map(([name, token]) => `  --pa-${kebab(name.replace(`theme.${theme}.`, ""))}: ${cssValue(token)};`).join("\n");
const swift = [...flat].filter(([name]) => name.startsWith("theme.")).map(([name, token]) => `  static let ${name.replace(/^theme\.(light|dark)\./, "$1_").replaceAll(".", "_")} = \"${resolveValue(token.$value)}\"`).join("\n");
const kotlin = [...flat].filter(([name]) => name.startsWith("theme.")).map(([name, token]) => `  const val ${name.replace(/^theme\.(light|dark)\./, "$1_").replaceAll(".", "_")} = \"${resolveValue(token.$value)}\"`).join("\n");
const androidColors = (theme) => [...flat].filter(([name, token]) => name.startsWith(`theme.${theme}.`) && token.$type === "color").map(([name, token]) => `  <color name="pa_${kebab(name.replace(`theme.${theme}.`, ""))}">${resolveValue(token.$value)}</color>`).join("\n");
const outputs = new Map([
  ["packages/web-storybook/generated/tokens.css", `/* Generated by design-system/scripts/build.mjs. Do not edit. */\n:root {\n${cssTokens}\n${themed("light")}\n}\n[data-theme=\"dark\"] {\n${themed("dark")}\n}\n@media (prefers-color-scheme: dark) { :root:not([data-theme]) {\n${themed("dark")}\n} }\n`],
  ["packages/web-storybook/generated/contracts.css", `/* Generated contract styles. */\n.pa-button { min-block-size: 2.75rem; border-radius: var(--pa-radius-md); border: 1px solid var(--pa-border-default); padding: var(--pa-space-2) var(--pa-space-4); font: var(--pa-type-label); transition: background var(--pa-motion-fast) var(--pa-motion-ease); }\n.pa-button--primary { background: var(--pa-action-primary); color: var(--pa-text-on-action); }\n.pa-button--destructive { background: var(--pa-action-danger); color: var(--pa-text-on-action); }\n.pa-button:focus-visible, .pa-input:focus-visible { outline: 3px solid var(--pa-border-focus); outline-offset: 2px; }\n.pa-input { min-block-size: 2.75rem; border: 1px solid var(--pa-border-default); border-radius: var(--pa-radius-md); padding: 0 var(--pa-space-3); color: var(--pa-text-primary); background: var(--pa-surface-base); }\n@media (prefers-reduced-motion: reduce) { .pa-button { transition: none; } }\n`],
  ["design-system/generated/contract-manifest.json", `${JSON.stringify({ ...contracts, themes: ["light", "dark"], breakpoints: { compact: 360, medium: 768, expanded: 1280 } }, null, 2)}\n`],
  ["packages/ios/PubAgentDesign/Sources/PubAgentDesign/DesignTokens.swift", `// Generated by design-system/scripts/build.mjs.\nimport Foundation\n\npublic enum DesignTokens {\n${swift}\n}\n\npublic enum ButtonContract {\n  public static let minimumHitTarget: CGFloat = 44\n  public static let variants = [\"primary\", \"secondary\", \"tertiary\", \"destructive\"]\n}\n\n#if canImport(SwiftUI)\nimport SwiftUI\npublic extension Color {\n  static let pubAgentActionPrimary = Color(pubAgentHex: DesignTokens.light_action_primary)\n  static let pubAgentSurface = Color(pubAgentHex: DesignTokens.light_surface_base)\n  init(pubAgentHex hex: String) {\n    let value = UInt64(hex.dropFirst(), radix: 16) ?? 0\n    self.init(.sRGB, red: Double((value >> 16) & 0xFF) / 255, green: Double((value >> 8) & 0xFF) / 255, blue: Double(value & 0xFF) / 255, opacity: 1)\n  }\n}\n#endif\n\n#if canImport(UIKit)\nimport UIKit\npublic extension UIColor {\n  static let pubAgentActionPrimary = UIColor(Color.pubAgentActionPrimary)\n  static let pubAgentSurface = UIColor(Color.pubAgentSurface)\n}\n#endif\n`],
  ["packages/kotlin/design-contract/src/commonMain/kotlin/io/pubagent/design/DesignTokens.kt", `// Generated by design-system/scripts/build.mjs.\npackage io.pubagent.design\n\nobject DesignTokens {\n${kotlin}\n}\n\nobject ButtonContract {\n  const val minimumHitTarget = 44\n  val variants = listOf(\"primary\", \"secondary\", \"tertiary\", \"destructive\")\n}\n`],
  ["packages/kotlin/design-contract/src/androidMain/res/values/design_tokens.xml", `<!-- Generated by design-system/scripts/build.mjs. -->\n<resources>\n${androidColors("light")}\n</resources>\n`],
  ["packages/kotlin/design-contract/src/androidMain/res/values-night/design_tokens.xml", `<!-- Generated by design-system/scripts/build.mjs. -->\n<resources>\n${androidColors("dark")}\n</resources>\n`]
  , ["packages/kotlin/design-contract/src/androidMain/res/values/design_contracts.xml", `<!-- Generated by design-system/scripts/build.mjs. -->\n<resources>\n  <dimen name=\"pa_minimum_hit_target\">44dp</dimen>\n  <dimen name=\"pa_control_radius\">10dp</dimen>\n  <style name=\"Widget.PubAgent.Button\">\n    <item name=\"android:minHeight\">@dimen/pa_minimum_hit_target</item>\n    <item name=\"android:backgroundTint\">@color/pa_action_primary</item>\n    <item name=\"android:textColor\">@color/pa_text_on_action</item>\n  </style>\n  <style name=\"Widget.PubAgent.TextField\">\n    <item name=\"android:minHeight\">@dimen/pa_minimum_hit_target</item>\n  </style>\n</resources>\n`]
]);
const check = process.argv.includes("--check");
for (const [file, content] of outputs) {
  const target = resolve(root, file);
  if (check) {
    let current = "";
    try { current = await readFile(target, "utf8"); } catch { /* generated file missing */ }
    if (current !== content) throw new Error(`Generated design artifact is stale: ${file}`);
  } else {
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, content);
  }
}
console.log(`${check ? "Verified" : "Generated"} ${outputs.size} design artifacts.`);
