// Generated by design-system/scripts/build.mjs.
import Foundation

public enum DesignTokens {
  static let light_text_primary = "#0F172A"
  static let light_text_secondary = "#334155"
  static let light_text_inverse = "#FFFFFF"
  static let light_text_onAction = "#FFFFFF"
  static let light_surface_base = "#FFFFFF"
  static let light_surface_raised = "#F8FAFC"
  static let light_surface_selected = "#EEF2FF"
  static let light_border_default = "#CBD5E1"
  static let light_border_focus = "#4338CA"
  static let light_action_primary = "#4338CA"
  static let light_action_primaryPressed = "#3730A3"
  static let light_action_danger = "#DC2626"
  static let light_status_error = "#DC2626"
  static let dark_text_primary = "#F8FAFC"
  static let dark_text_secondary = "#CBD5E1"
  static let dark_text_inverse = "#0F172A"
  static let dark_text_onAction = "#FFFFFF"
  static let dark_surface_base = "#0F172A"
  static let dark_surface_raised = "#334155"
  static let dark_surface_selected = "#3730A3"
  static let dark_border_default = "#64748B"
  static let dark_border_focus = "#4F46E5"
  static let dark_action_primary = "#4F46E5"
  static let dark_action_primaryPressed = "#4338CA"
  static let dark_action_danger = "#DC2626"
  static let dark_status_error = "#DC2626"
}

public enum ButtonContract {
  public static let minimumHitTarget: CGFloat = 44
  public static let variants = ["primary", "secondary", "tertiary", "destructive"]
}

#if canImport(SwiftUI)
import SwiftUI
public extension Color {
  static let pubAgentActionPrimary = Color(pubAgentHex: DesignTokens.light_action_primary)
  static let pubAgentSurface = Color(pubAgentHex: DesignTokens.light_surface_base)
  init(pubAgentHex hex: String) {
    let value = UInt64(hex.dropFirst(), radix: 16) ?? 0
    self.init(.sRGB, red: Double((value >> 16) & 0xFF) / 255, green: Double((value >> 8) & 0xFF) / 255, blue: Double(value & 0xFF) / 255, opacity: 1)
  }
}
#endif

#if canImport(UIKit)
import UIKit
public extension UIColor {
  static let pubAgentActionPrimary = UIColor(Color.pubAgentActionPrimary)
  static let pubAgentSurface = UIColor(Color.pubAgentSurface)
}
#endif
