// Generated by design-system/scripts/build.mjs.
package io.pubagent.design

object DesignTokens {
  const val light_text_primary = "#0F172A"
  const val light_text_secondary = "#334155"
  const val light_text_inverse = "#FFFFFF"
  const val light_text_onAction = "#FFFFFF"
  const val light_surface_base = "#FFFFFF"
  const val light_surface_raised = "#F8FAFC"
  const val light_surface_selected = "#EEF2FF"
  const val light_border_default = "#CBD5E1"
  const val light_border_focus = "#4338CA"
  const val light_action_primary = "#4338CA"
  const val light_action_primaryPressed = "#3730A3"
  const val light_action_danger = "#DC2626"
  const val light_status_error = "#DC2626"
  const val dark_text_primary = "#F8FAFC"
  const val dark_text_secondary = "#CBD5E1"
  const val dark_text_inverse = "#0F172A"
  const val dark_text_onAction = "#FFFFFF"
  const val dark_surface_base = "#0F172A"
  const val dark_surface_raised = "#334155"
  const val dark_surface_selected = "#3730A3"
  const val dark_border_default = "#64748B"
  const val dark_border_focus = "#4F46E5"
  const val dark_action_primary = "#4F46E5"
  const val dark_action_primaryPressed = "#4338CA"
  const val dark_action_danger = "#DC2626"
  const val dark_status_error = "#DC2626"
}

object ButtonContract {
  const val minimumHitTarget = 44
  val variants = listOf("primary", "secondary", "tertiary", "destructive")
}
